ls:
    src:
        .dir: kebab-case
        .ts: kebab-case
        .d.ts: kebab-case
        .json: kebab-case
        .svelte: PascalCase
    test:
        .dir: kebab-case
        .ts: kebab-case
        .d.ts: kebab-case
        .config.ts: kebab-case
        .json: kebab-case
        .test.ts: kebab-case
        .svelte.test.ts: PascalCase
