---
when:
    - event: manual

steps:
    - name: publish-container-image
      image: woodpeckerci/plugin-docker-buildx:6.0.2
      settings:
          repo:
              from_secret: repository
          registry:
              from_secret: registry
          dockerfile: Dockerfile
          platforms: linux/arm64
          build_args:
              VITE_POCKETBASE_BASE_URL: https://pb.seniorenzocken.net
              VITE_TRPC_SERVER_URL: https://www.seniorenzocken.net/api/trpc
          tags:
              - latest
              - ${CI_COMMIT_SHA}
          username:
              from_secret: username
          password:
              from_secret: access_token

depends_on:
    - test
