---
when:
    - event: manual

steps:
    - name: build-browser-application
      image: node:24.2.0
      environment:
          VITE_POCKETBASE_BASE_URL: https://pb.seniorenzocken.net
      commands:
          - npm clean-install
          - npx rust-just build-browser-application

    - name: publish-container-image
      image: woodpeckerci/plugin-docker-buildx:6.0.1
      settings:
          repo:
              from_secret: repository
          registry:
              from_secret: registry
          dockerfile: docker/browser-application/Dockerfile
          platforms: linux/arm64
          tags:
              - latest
              - ${CI_COMMIT_SHA}
          username:
              from_secret: username
          password:
              from_secret: access_token

depends_on:
    - test
