---
when:
    - event: [push, manual]

steps:
    - name: test
      image: node:24.3.0
      commands:
          - npm clean-install
          - npx just test
          - npx just build-browser-application
          - npx just generate-database-migrations

    - name: fail-on-git-status
      image: alpine/git:2.49.0
      commands:
          - git status
          - test -z "$(git status --porcelain)"
