---
when:
    - event: [push, manual]

steps:
    - name: test
      image: node:24.3.0
      commands:
          - npm clean-install
          - npx just test
          - npx just build-browser-application
