---
when:
    - event: [push, manual]

steps:
    - name: test
      image: node:24.2.0
      commands:
          - npm clean-install
          - npx rust-just test
          - npx rust-just build-browser-application
