name: Main

on: [push]

jobs:
    tests:
        name: Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Setup Node.js
              uses: ./.github/actions/setup-nodejs
            - name: Check source code
              run: |
                  npm run lint
                  npm run compile
            - name: Run unit tests
              run: npm run test:unit:coverage

    end-to-end-tests:
        name: End-to-end tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  lfs: true
            - name: Setup Node.js
              uses: ./.github/actions/setup-nodejs
            - name: Install Playwright
              run: npx playwright install --with-deps chromium
            - name: Run tests
              run: npm run test:end-to-end
            - uses: actions/upload-artifact@v3
              if: ${{ failure() }}
              with:
                  name: playwright-html-report
                  path: target/test-output/end-to-end/html-report/
                  retention-days: 7

    deploy-to-netlify:
        name: Deploy to Netlify
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        needs: [tests, end-to-end-tests]
        concurrency:
            group: deploy-to-netlify
        env:
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
            NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  lfs: true
            - name: Setup Node.js
              uses: ./.github/actions/setup-nodejs
            - name: Deploy to Netlify
              run: npx netlify deploy --build --message "Deploy from GitHub Actions" --prod
